/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.microstrategy.database.hbase.view;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author wlu
 */
public class ClusterStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClusterStatusPanel
     */
    public ClusterStatusPanel() {
        initComponents();
        jSplitPane2.setDividerLocation(0.5);
    }
    private ChartPanel mMemSizeEachTableRsChart = null;

    public void setMemSizeEachTableRSChart(ChartPanel iChartPanel) {
        if (iChartPanel == null) {
            return;
        }
        if (mMemSizeEachTableRsChart != null) {
            mpMemSizePanel.remove(mMemSizeEachTableRsChart);
        }
        mMemSizeEachTableRsChart = iChartPanel;
        mpMemSizePanel.add(mMemSizeEachTableRsChart);
        mpMemSizePanel.revalidate();
        mpMemSizePanel.repaint();
    }
    
    private ChartPanel mNumberOfRegionEachTableRsChart = null;
    public void setNumberOfRegionEachTableRsChart(ChartPanel iChartPanel){
        if(iChartPanel == null){
            return;
        }
        if(mNumberOfRegionEachTableRsChart != null){
            mRegionNumberPanel.remove(mNumberOfRegionEachTableRsChart);
        }
        mNumberOfRegionEachTableRsChart = iChartPanel;
        mRegionNumberPanel.add(mNumberOfRegionEachTableRsChart);
        mRegionNumberPanel.revalidate();
        mRegionNumberPanel.repaint();
    }
    
    
    private ChartPanel mStoreFileSizeEachTableRsChart = null;
    private ChartPanel mStoreFileNumbEachTableRsChart = null;

    public void setStoreFileEachTableRSChart(ChartPanel iChartPanel, ChartPanel iChartPanel2) {
        if (iChartPanel == null || iChartPanel2 == null) {
            return;
        }
        // store size
        if (mStoreFileSizeEachTableRsChart != null) {
            mpStoreFileSizzPanel.remove(mStoreFileSizeEachTableRsChart);
        }

        mStoreFileSizeEachTableRsChart = iChartPanel;
        mpStoreFileSizzPanel.add(mStoreFileSizeEachTableRsChart);
        // store number
        if (mStoreFileNumbEachTableRsChart != null) {
            mpStoreFileNumberPanel.remove(mStoreFileNumbEachTableRsChart);
        }
        mStoreFileNumbEachTableRsChart = iChartPanel2;
        mpStoreFileNumberPanel.add(mStoreFileNumbEachTableRsChart);

        mpStoreFileSizzPanel.revalidate();
        mpStoreFileSizzPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabPanel = new javax.swing.JTabbedPane();
        mpMemSizePanel = new javax.swing.JPanel();
        mRegionNumberPanel = new javax.swing.JPanel();
        mpStoreFilePanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        mpStoreFileSizzPanel = new javax.swing.JPanel();
        mpStoreFileNumberPanel = new javax.swing.JPanel();

        mpMemSizePanel.setLayout(new java.awt.BorderLayout());
        jTabPanel.addTab("MemSize", mpMemSizePanel);

        mRegionNumberPanel.setLayout(new java.awt.BorderLayout());
        jTabPanel.addTab("RegionNum", mRegionNumberPanel);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        mpStoreFileSizzPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane2.setTopComponent(mpStoreFileSizzPanel);

        mpStoreFileNumberPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane2.setRightComponent(mpStoreFileNumberPanel);

        javax.swing.GroupLayout mpStoreFilePanelLayout = new javax.swing.GroupLayout(mpStoreFilePanel);
        mpStoreFilePanel.setLayout(mpStoreFilePanelLayout);
        mpStoreFilePanelLayout.setHorizontalGroup(
            mpStoreFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        mpStoreFilePanelLayout.setVerticalGroup(
            mpStoreFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        jTabPanel.addTab("StoreFile", mpStoreFilePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabPanel)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabPanel;
    private javax.swing.JPanel mRegionNumberPanel;
    private javax.swing.JPanel mpMemSizePanel;
    private javax.swing.JPanel mpStoreFileNumberPanel;
    private javax.swing.JPanel mpStoreFilePanel;
    private javax.swing.JPanel mpStoreFileSizzPanel;
    // End of variables declaration//GEN-END:variables
}
