/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.microstrategy.database.hbase.view;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author wlu
 */
public class RegionServerStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegionServerStatus
     */
    public RegionServerStatusPanel() {
        initComponents();
    }
    private ChartPanel mHeapSizeChart = null;

    public void setHeapSizeChart(ChartPanel iHeapsizechart) {
        if (iHeapsizechart == null) {
            return;
        }
        if (mHeapSizeChart == null) {
        } else {
            pHeapSizePanel.remove(mHeapSizeChart);
        }
        mHeapSizeChart = iHeapsizechart;
        pHeapSizePanel.add(mHeapSizeChart);
        pHeapSizePanel.revalidate();
        pHeapSizePanel.repaint();
    }
    
    private ChartPanel mStoreFileStatusChart = null;
    public void setStoreFileStatusChart(ChartPanel istorefilestatuschart){
        if(istorefilestatuschart == null){
            return;
        }
        if(mStoreFileStatusChart == null){
            
        }else{
            pStoreFilePanel.remove(mStoreFileStatusChart);
        }
        mStoreFileStatusChart = istorefilestatuschart;
        pStoreFilePanel.add(mStoreFileStatusChart);
        pStoreFilePanel.revalidate();
        pStoreFilePanel.repaint();
    }
    
    private ChartPanel mNumRRChart= null;
    public void setNumRRChart(ChartPanel iNumRRChart){
        if(iNumRRChart == null){
            return;
        }
        if(mNumRRChart !=null){
            pRequestPanel.remove(mNumRRChart);
        }
        mNumRRChart = iNumRRChart;
        pRequestPanel.add(mNumRRChart);
        pRequestPanel.revalidate();
        pRequestPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pHeapSizePanel = new javax.swing.JPanel();
        pStoreFilePanel = new javax.swing.JPanel();
        pRequestPanel = new javax.swing.JPanel();
        pMemFlush = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        pHeapSizePanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("HeapSize", pHeapSizePanel);

        pStoreFilePanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("StoreFiles", pStoreFilePanel);

        pRequestPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Requests", pRequestPanel);

        javax.swing.GroupLayout pMemFlushLayout = new javax.swing.GroupLayout(pMemFlush);
        pMemFlush.setLayout(pMemFlushLayout);
        pMemFlushLayout.setHorizontalGroup(
            pMemFlushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        pMemFlushLayout.setVerticalGroup(
            pMemFlushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MemFlush", pMemFlush);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pHeapSizePanel;
    private javax.swing.JPanel pMemFlush;
    private javax.swing.JPanel pRequestPanel;
    private javax.swing.JPanel pStoreFilePanel;
    // End of variables declaration//GEN-END:variables
}
